# Manipulación de Dimensiones en Arrays con NumPy

**Curso:** Python para Ciencia de Datos
**Tema:** Manejo de dimensiones en NumPy
**Fecha:** 02-03 de Octubre, 2025

---

## Introducción

Las dimensiones en NumPy transforman la manera de trabajar con datos. Entender cómo manejar y manipular datos en múltiples dimensiones es crucial para cualquier científico de datos.

In [2]:
import numpy as np

## 1. Escalar (Dimensión 0)

Un escalar es un array de dimensión 0, es decir, un solo valor.

**Ejemplo:** Temperatura de un día específico

In [ ]:
escalar = np.array(42)
print(escalar)
print(type(escalar))
print("-" * 50)

## 2. Vector (Dimensión 1)

Un vector es una secuencia ordenada de valores. En NumPy, los arrays de una sola dimensión se llaman vectores.

**Ejemplo:** Temperaturas de toda una semana

**Nota:** La creación de listas o tuplas para NumPy es muy similar, sin embargo, el término correcto cuando estamos trabajando con array de una sola dimensión es **vector**.

In [ ]:
vector = np.array([30, 29, 35, 31, 33, 36, 42])
print(vector)
print(type(vector))
print("-" * 50)

## 3. Matriz (Dimensión 2)

Cuando queremos trabajar con 2 dimensiones hacemos referencia al concepto de matriz.

**Regla práctica:** Una forma de saber qué tipo de matriz es se puede determinar por la cantidad de corchetes que tenga nuestro objeto `numpy.array`.

In [6]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)
print(type(matriz))
print("-" * 50)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
--------------------------------------------------


## 4. Tensor (Dimensión 3+)

Cuando trabajamos con 3 dimensiones hacemos referencia al concepto de **tensor**.

In [5]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])
print(tensor)
print(type(tensor))
print("-" * 50)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>
--------------------------------------------------


---

## Métodos de Creación de Arrays

Según el curso, existen **6 mecanismos generales** para crear un array de NumPy:

1. Conversión desde otras estructuras de datos (listas, tuplas)
2. Funciones de creación de arrays (como crear una matriz de 0)
3. Replicación (unión o mutación) de arrays existentes
4. Lectura de arrays desde disco (formatos estándar o personalizados)
5. Creación de arrays desde bytes crudos mediante cadenas o buffers
6. Uso de funciones especiales de bibliotecas de álgebra lineal

### Vector con `arange()`

Creación de un VECTOR con el método `arange()`

In [6]:
array_range = np.arange(10)
print(array_range)
print(type(array_range))
print("-" * 50)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
--------------------------------------------------


### Matriz Identidad con `eye()`

Creación de una matriz IDENTIDAD, donde se usa el método `eye()` y se le pasa como argumento el número de la matriz.

In [3]:
matriz_identidad = np.eye(3)
print(matriz_identidad)
print(type(matriz_identidad))
print("-" * 50)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
--------------------------------------------------


### Matriz Diagonal con `diag()`

Creación de matriz diagonal, funciona como la matriz identidad pero solo con un valor determinado por nosotros dentro de las filas.

In [ ]:
matriz_diagonal = np.diag([1, 2, 3, 4, 5, 6, 7])
print(matriz_diagonal)
print(type(matriz_diagonal))
print("-" * 50)

### Matriz con Valores Aleatorios con `random()`

Creación de una matriz RANDOM, nos da la información de una matriz con valores aleatorios.

**Recibe como argumento el tamaño de la matriz:**
- El primer argumento son las filas
- El segundo argumento son las columnas

In [4]:
matriz_random = np.random.random((3, 3))
print(matriz_random)
print(type(matriz_random))

[[0.69579771 0.29141694 0.90999765]
 [0.05961415 0.27844786 0.63708409]
 [0.64075028 0.91037489 0.7308847 ]]
<class 'numpy.ndarray'>


---

## Reto Personal

Investiga cuáles otros métodos de NumPy existen para crear arrays.

**Sugerencias para explorar:**
- `np.zeros()` - Matriz de ceros
- `np.ones()` - Matriz de unos
- `np.full()` - Matriz con valor constante
- `np.linspace()` - Secuencia con espaciado lineal
- `np.empty()` - Matriz sin inicializar (más rápida)
- `np.random.randint()` - Enteros aleatorios

In [8]:
# Creación de un vector de ceros
vector_zeros = np.zeros(4)
print(vector_zeros)
print("-" * 50)

# Creación vector de unos
vector_ones = np.ones(4)
print(vector_ones)
print("-" * 50)

# Creación vector con valor constante, primer argumento como cantidad de columnas y segundo como valor
vector_full_constante = np.full(5, 2)
print(vector_full_constante)
print("-" * 50)

# Creación vector con valores cantidad de valores exactos
vector_linspace = np.linspace(0, 10, 11)
print(vector_linspace)
print("-" * 50)

# Vector sin inicializar (números basura), sirve para no limpiar la memoria
vector_empty = np.empty(6)
print(vector_empty)
print("-" * 50)

# Vector de enteros aleatorios, primer argumento es el valor minimo, el segundo es el valor maximo y el tercero es la cantidad de valores
vector_numeros_enteros = np.random.randint(low=0, high=15, size=20)
print(vector_numeros_enteros)
print("-" * 50)

# Existe la forma de crear las dimensiones de un array (matriz) desde un método sin tener que usar la manualidad
matriz_metodo = np.arange(1, 13).reshape(3, 4)
print(matriz_metodo)

[0. 0. 0. 0.]
--------------------------------------------------
[1. 1. 1. 1.]
--------------------------------------------------
[2 2 2 2 2]
--------------------------------------------------
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
--------------------------------------------------
[0. 0. 0. 0. 0. 0.]
--------------------------------------------------
[ 3  6  5 10  1  6 11  5  2 14 10  6  4  3  9 13  5 14  4 10]
--------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


---

## Resumen

- **Escalar (0D):** Un solo valor
- **Vector (1D):** Lista de valores
- **Matriz (2D):** Tabla (filas × columnas)
- **Tensor (3D+):** Estructuras multidimensionales
- **6 formas de crear arrays:** Conversión, funciones, replicación, lectura, bytes, bibliotecas especializadas
- **Funciones clave:** `arange()`, `eye()`, `diag()`, `random()`

**Próximos pasos:** Practicar indexación y slicing de arrays para manipular subconjuntos de datos.