# Álgebra Lineal con NumPy

**Curso:** Python para Ciencia de Datos
**Tema:** Operaciones de Álgebra Lineal
**Fecha:** 03 de Octubre, 2025

---

## Introducción

El álgebra lineal es una rama fundamental de las matemáticas que se centra en el estudio de los vectores, las matrices y las transformaciones lineales. NumPy proporciona herramientas para resolver sistemas de ecuaciones lineales, realizar transformaciones geométricas y modelar problemas en diversas áreas de la ciencia y la ingeniería.

### Aplicaciones

- Gráficos por computadora
- Procesamiento de imágenes
- Machine Learning
- Física y simulaciones
- Optimización de sistemas complejos

In [ ]:
import numpy as np

## Conceptos Básicos

### Vectores
Objetos que tienen magnitud y dirección. Se representan como una lista de números (coordenadas).

### Matrices
Arreglos bidimensionales de números que representan transformaciones lineales.

### Transformaciones Lineales
Funciones que toman vectores como entrada y producen otros vectores, respetando suma y multiplicación por escalar.

### Espacios Vectoriales
Conjuntos de vectores que pueden sumarse entre sí y multiplicarse por escalares.

---

## 1. Suma de Matrices

La suma de matrices se realiza **elemento por elemento**. Ambas matrices deben tener las mismas dimensiones.

**Ejemplo:**

$$ \underbrace{\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}}_{A} + \underbrace{\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}}_{B} = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix} $$

In [ ]:
# Definir dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma de matrices
suma = A + B
print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
print("\nSuma A + B:\n", suma)

---

## 2. Multiplicación de Matrices

La multiplicación de matrices combina **filas de la primera matriz con columnas de la segunda**.

**Importante:** El número de columnas de A debe ser igual al número de filas de B.

**Fórmula:**
- Resultado[i,j] = suma de (A[i,:] * B[:,j])

In [ ]:
# Multiplicación de matrices (dot product)
producto = np.dot(A, B)
print("Producto A · B:\n", producto)

# Alternativa (Python 3.5+)
producto_alt = A @ B
print("\nProducto A @ B (mismo resultado):\n", producto_alt)

---

## 3. Transposición de Matrices

La transposición intercambia **filas por columnas**.

**Ejemplo:**

$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \quad A^T = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix} $$

In [ ]:
# Transposición
transpuesta = A.T
print("Matriz A:\n", A)
print("\nTranspuesta A^T:\n", transpuesta)

---

## 4. Determinante de una Matriz

El determinante es un valor único calculado a partir de una **matriz cuadrada**.

**Para matriz 2x2:**

$$ \det(A) = (a \cdot d) - (b \cdot c) $$

**Utilidad:**
- Si det = 0, la matriz no tiene inversa
- Indica si un sistema de ecuaciones tiene solución única

In [ ]:
# Determinante
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)
print("\n¿A tiene inversa?:", determinante != 0)

---

## 5. Inversa de una Matriz

La matriz inversa A^(-1) cumple que: **A · A^(-1) = I** (matriz identidad)

**Solo existe si det(A) ≠ 0**

In [ ]:
# Inversa de la matriz
inversa = np.linalg.inv(A)
print("Matriz A:\n", A)
print("\nInversa A^(-1):\n", inversa)

# Verificación: A · A^(-1) = I
verificacion = np.dot(A, inversa)
print("\nVerificación A · A^(-1) ≈ I:\n", np.round(verificacion, 10))

---

## 6. Valores y Vectores Propios

**Valores propios (eigenvalues):** Escalares λ que satisfacen: A·v = λ·v

**Vectores propios (eigenvectors):** Vectores v que solo cambian de escala al aplicar A

**Aplicaciones:**
- Compresión de datos (PCA)
- Análisis de sistemas dinámicos
- Reconocimiento facial

In [ ]:
# Valores y vectores propios
valores_propios, vectores_propios = np.linalg.eig(A)

print("Valores propios de A:\n", valores_propios)
print("\nVectores propios de A:\n", vectores_propios)

---

## 7. Resolución de Sistemas de Ecuaciones Lineales

Resolver sistemas del tipo: **A·X = B**

**Ejemplo:**

$$ \begin{cases} x + 2y = 1 \\ 3x + 4y = 2 \end{cases} $$

**Se representa como:**

$$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \cdot \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} $$


In [ ]:
# Sistema de ecuaciones: A·X = B
B = np.array([1, 2])

# Resolver para X
X = np.linalg.solve(A, B)
print("Sistema: A·X = B")
print("Matriz A:\n", A)
print("\nVector B:", B)
print("\nSolución X:", X)

# Verificación
verificacion = np.dot(A, X)
print("\nVerificación A·X =", verificacion, "(debe ser igual a B)")

---

## Resumen de Funciones NumPy para Álgebra Lineal

| Operación | Función | Ejemplo |
|-----------|---------|---------|
| Suma | `A + B` | Suma elemento por elemento |
| Producto | `np.dot(A, B)` o `A @ B` | Multiplicación matricial |
| Transpuesta | `A.T` | Intercambio filas/columnas |
| Determinante | `np.linalg.det(A)` | Valor escalar |
| Inversa | `np.linalg.inv(A)` | A^(-1) |
| Valores propios | `np.linalg.eig(A)` | Eigenvalues y eigenvectors |
| Resolver sistema | `np.linalg.solve(A, B)` | A·X = B |

**Próximos pasos:** Aplicar álgebra lineal en transformaciones geométricas y machine learning.

---

## Ejercicios de Práctica

Resuelve los siguientes ejercicios para consolidar tu aprendizaje:

In [ ]:
# EJERCICIO 1: Operaciones Básicas
# Dadas las matrices:
C = np.array([[2, 0], [1, 3]])
D = np.array([[1, 4], [2, 1]])

# Calcula:
# a) C + D
# b) C - D
# c) 3 * C (multiplicación por escalar)
# d) C · D (producto matricial)

# Tu código aquí:

# Suma de matrices
suma = C + D
print("Matriz C:\n", C)
print("\nMatriz D:\n", D)
print("\nSuma C + D:\n", suma)
print('-' * 200)

# Resta de matrices
resta = C - D
print("\nResta C - D:\n", resta)
print('-' * 200)

# Multiplicación de escalar con matriz (dot product)
producto_escalar = np.dot(3, C)
print("Producto 3 · C:\n", producto_escalar)

# Multiplicación de matrices (dot product)
producto_matricial = np.dot(C, D)
print("Producto C · D:\n", producto_matricial)


In [ ]:
# EJERCICIO 2: Propiedades de la Transposición
# Dada la matriz:
E = np.array([[1, 2, 3], [4, 5, 6]])

# Verifica las siguientes propiedades:
# a) (E^T)^T = E (la transpuesta de la transpuesta es la matriz original)
# b) Imprime las dimensiones de E y E^T
# c) ¿Qué pasa si intentas multiplicar E · E? ¿Y E · E^T?

# Tu código aquí:

print(f'Matriz E:\n{E}')
print('-' * 200)

Transpuesta_de_tranpuesta_E = (E.T).T
print(f'Transpuesta de la transpuesta de la matriz E es:\n{Transpuesta_de_tranpuesta_E}')
print('-' * 200)

Transpuesta_E = E.T
print(f'Transpuesta de la matriz E es:\n{Transpuesta_E}')
print('-' * 200)

print(f'Dimensiones de E: {E.shape}')
print(f'Dimensiones de E^T: {Transpuesta_E.shape}')
print('-' * 200)

'''
#! No te deja obtener el producto matricial entre E y E
producto_matricial_E = np.dot(E, E)
print(f"Producto matricial entre E y E:\n{producto_matricial_E}")
'''

#! Si dejo hacer la multiplicación de matrices, sin embargo, porque la matriz del primer atributo tiene la misma cantidad de filas que la matriz del segundo atributo
producto_matricial = np.dot(E, Transpuesta_E)
print(f"Producto matricial entre E y E^T:\n{producto_matricial}")


In [37]:
# EJERCICIO 3: Determinante e Inversa
# Dada la matriz:
F = np.array([[4, 7], [2, 6]])
G = np.array([[1, 2], [2, 4]])

# a) Calcula el determinante de F
# b) Si det(F) ≠ 0, calcula la inversa
# c) Verifica que F · F^(-1) = I (matriz identidad)
# d) ¿Qué pasa si intentas calcular la inversa de [[1, 2], [2, 4]]?
#    (Pista: primero calcula su determinante)

# Tu código aquí:

# Determinante
determinante = np.linalg.det(F)
print("Determinante de F:", determinante)
print("\n¿F tiene inversa?:", determinante != 0)
print('-' * 200)

# Inversa de F ya que la determinante es != a 0

# Inversa de la matriz
inversa = np.linalg.inv(F)
print("Matriz F:\n", F)
print("\nInversa F^(-1):\n", inversa)
print('-' * 200)

# Verificación: F · F^(-1) = I
verificacion = np.dot(F, inversa)
print("\nVerificación F · F^(-1) ≈ I:\n", np.round(verificacion, 10))
print('-' * 200)

# Verificando el punto D .. Para ello cree la matriz G
# Determinante
determinante = np.linalg.det(G)
print("Determinante de G:", determinante)
print("\n¿G tiene inversa?:", determinante != 0)
print('-' * 200)


'''
# Inversa de la matriz
inversa = np.linalg.inv(G)
print("Matriz G:\n", G)
print("\nInversa G^(-1):\n", inversa)
print('-' * 200)
'''
# Identificamos que no se puede calcular, puesto a que es una matriz Singular, adicional que su determinante es igual a 0

Determinante de F: 10.000000000000002

¿F tiene inversa?: True
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Matriz F:
 [[4 7]
 [2 6]]

Inversa F^(-1):
 [[ 0.6 -0.7]
 [-0.2  0.4]]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verificación F · F^(-1) ≈ I:
 [[ 1. -0.]
 [ 0.  1.]]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Determinante de G: 0.0

¿G tiene inversa?: False
----------------------------------------------------------------------------------------------------------------------------------------------------------------

'\n# Inversa de la matriz\ninversa = np.linalg.inv(G)\nprint("Matriz G:\n", G)\nprint("\nInversa G^(-1):\n", inversa)\nprint(\'-\' * 200)\n'