# Ejercicio practico para conteo de información

In [3]:
import numpy as np
# Respuestas de los clientes al producto
survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente"])

# Obtener valores unicos con atributo unique()
print(np.unique(survey_responses))

unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
['bueno' 'excelente' 'malo']
[4 3 3]


In [5]:
# Vistas

array_x = np.arange(10)
vista_y = array_x[1:3]

print(array_x)
print(vista_y)

array_x[1:3] = [10,11]

print(array_x)
print(vista_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [8]:
# Crear copias
array_x = np.arange(10)
print(array_x)

copy_x = array_x[[1,2]]
print(copy_x)

array_x[1:3] = [10, 11]
print(array_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
