# Manipulación de Matrices en NumPy

**Curso:** Python para Ciencia de Datos
**Tema:** Transposición, Reshape, Inversión y Aplanamiento de Arrays
**Fecha:** 07 de Octubre, 2025

---

## Introducción

La manipulación de matrices es fundamental en ciencia de datos y álgebra lineal. NumPy proporciona operaciones eficientes para:

- **Transponer:** Intercambiar filas y columnas
- **Reshape:** Cambiar dimensiones sin modificar datos
- **Invertir:** Revertir el orden de elementos
- **Aplanar:** Convertir arrays multidimensionales a 1D

Estas operaciones son esenciales para procesamiento de datos, machine learning y álgebra lineal.

In [ ]:
import numpy as np

---

## 1. Transposición de Matrices

**Definición:** La transposición intercambia filas y columnas de una matriz.

**Operación:** Fila i se convierte en Columna i

**Sintaxis:** `matriz.T`

### Aplicaciones
- Álgebra lineal (multiplicación de matrices)
- Rotación de imágenes
- Análisis de datos (cambiar organización de tablas)

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

transpuesta_matriz = matriz.T

print("Matriz original:")
print(matriz)
print('-' * 100)
print("Matriz transpuesta:")
print(transpuesta_matriz)

### Visualización de Transposición

Original (3x3):\
[1 2 3] \
[4 5 6] \
[7 8 9] \
Transpuesta (3x3):\
[1 4 7] \
[2 5 8] \
[3 6 9]

Fila 1 → Columna 1\
Fila 2 → Columna 2\
Fila 3 → Columna 3

**Nota:** Las dimensiones se invierten: (m, n) → (n, m)


---

## 2. Cambiar la Forma (Reshape)

**Definición:** Reorganiza los elementos de un array en nuevas dimensiones SIN modificar los datos.

**Regla crítica:** El **número total de elementos** debe permanecer constante.

**Sintaxis:** `array.reshape(filas, columnas)`

In [ ]:
# Array unidimensional de 1 a 12
array = np.arange(1, 13)
print("Array original (12 elementos):")
print(array)
print("Forma:", array.shape)
print('-' * 100)

# Reorganizar en matriz 3x4
reshape_array = array.reshape(3, 4)
print("Reshaped a 3x4:")
print(reshape_array)
print("Forma:", reshape_array.shape)

### Reglas de Reshape

**Válido (12 elementos):**
- `reshape(3, 4)` ✅ (3 × 4 = 12)
- `reshape(4, 3)` ✅ (4 × 3 = 12)
- `reshape(2, 6)` ✅ (2 × 6 = 12)
- `reshape(1, 12)` ✅ (1 × 12 = 12)

**Inválido:**
- `reshape(5, 3)` ❌ (5 × 3 = 15 ≠ 12)
- `reshape(3, 3)` ❌ (3 × 3 = 9 ≠ 12)

**Error típico:**

# ValueError: cannot reshape array of size 12 into shape (3,5)

---

### Reshape Automático con -1

NumPy puede **inferir** una dimensión automáticamente usando `-1`:

In [ ]:
array = np.arange(1, 13)

# Especifica 3 filas, NumPy calcula columnas automáticamente
auto_reshape = array.reshape(3, -1)
print("Reshape(3, -1) → NumPy calcula que deben ser 4 columnas:")
print(auto_reshape)
print("Forma:", auto_reshape.shape)

# Especifica 4 columnas, NumPy calcula filas
auto_reshape2 = array.reshape(-1, 4)
print("\nReshape(-1, 4) → NumPy calcula que deben ser 3 filas:")
print(auto_reshape2)
print("Forma:", auto_reshape2.shape)

---

## 3. Inversión de Arrays

**Definición:** Revertir el orden de los elementos (el primero se vuelve último).

**Sintaxis:** `array[::-1]` (slicing con paso negativo)

### Aplicaciones
- Procesamiento de señales
- Reversión de secuencias temporales
- Algoritmos de ordenamiento

In [ ]:
array = np.arange(1, 13)
print("Array original:")
print(array)

# Invertir usando slicing
reversed_array = array[::-1]
print("\nArray invertido:")
print(reversed_array)

# También funciona en matrices (invierte filas)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatriz original:")
print(matriz)

print("\nMatriz con filas invertidas:")
print(matriz[::-1])

print("\nMatriz con columnas invertidas:")
print(matriz[:, ::-1])

### Notación de Slicing: `[start:stop:step]`

array[::1]   # Normal (paso +1) \
array[::-1]  # Invertido (paso -1) \
array[::2]   # Cada 2 elementos \
array[::-2]  # Invertido, cada 2 elementos

**Truco:** step=-1 significa "ir hacia atrás"

---

## 4. Aplanamiento (Flattening)

**Definición:** Convertir un array multidimensional en un array unidimensional.

**Métodos:**
- `flatten()` → Crea una **copia**
- `ravel()` → Crea una **vista** (más eficiente)

### Aplicaciones
- Entrada para algoritmos de ML (requieren vectores 1D)
- Agregación de datos
- Serialización de datos

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriz original:")
print(matriz)
print("Forma:", matriz.shape)
print('-' * 100)

# flatten() - Crea copia
flattened_array = matriz.flatten()
print("Array aplanado con flatten():")
print(flattened_array)
print("Forma:", flattened_array.shape)

### Diferencia: `flatten()` vs `ravel()`

| Método | Comportamiento | Velocidad | Uso |
|--------|----------------|-----------|-----|
| `flatten()` | Siempre crea copia | Más lento | Cuando necesitas independencia |
| `ravel()` | Intenta crear vista | Más rápido | Cuando solo lees datos |

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])

# flatten() - Copia
flat_copy = matriz.flatten()
flat_copy[0] = 999
print("Original después de modificar flatten():")
print(matriz)  # NO cambió

print('-' * 100)

# ravel() - Vista (cuando es posible)
flat_view = matriz.ravel()
flat_view[0] = 999
print("Original después de modificar ravel():")
print(matriz)  # SÍ cambió (es una vista)

---

## Resumen de Operaciones

| Operación | Sintaxis | Qué hace | Crea copia |
|-----------|----------|----------|------------|
| Transponer | `matriz.T` | Intercambia filas ↔ columnas | No (vista) |
| Reshape | `array.reshape(m, n)` | Cambia dimensiones | No (vista) |
| Invertir | `array[::-1]` | Revierte orden | Sí |
| Aplanar | `matriz.flatten()` | 2D → 1D | Sí |
| Aplanar | `matriz.ravel()` | 2D → 1D | No (intenta vista) |

---

## Aplicaciones en Ciencia de Datos

### Ejemplo 1: Preparación de Datos para Machine Learning

Convertir imagen de matriz a vector para entrenar un modelo.

In [ ]:
# Simular una imagen en escala de grises 28x28 píxeles
np.random.seed(42)
imagen = np.random.randint(0, 256, size=(28, 28))

print("Imagen original (matriz 28x28):")
print("Forma:", imagen.shape)
print("Primeros 5x5 píxeles:")
print(imagen[:5, :5])

# Para entrenar modelos como redes neuronales, necesitamos un vector 1D
imagen_flat = imagen.flatten()

print("\nImagen aplanada (vector 784):")
print("Forma:", imagen_flat.shape)
print("Primeros 10 valores:", imagen_flat[:10])

# Este vector es la entrada que recibiría un modelo de ML
print(f"\nTotal de features: {len(imagen_flat)}")

**Explicación:**
- Imágenes MNIST son 28×28 = 784 píxeles
- Modelos como regresión logística o redes neuronales simples requieren entrada 1D
- `flatten()` convierte la matriz 2D en un vector de 784 elementos

### Ejemplo 2: Transposición para Análisis de Datos

Reorganizar datos de estudiantes para diferentes análisis.

In [ ]:
# Dataset: 4 estudiantes × 3 materias
# Filas = Estudiantes, Columnas = Materias
calificaciones = np.array([
    [85, 90, 78],  # Estudiante 1
    [92, 88, 95],  # Estudiante 2
    [78, 85, 82],  # Estudiante 3
    [90, 92, 88]   # Estudiante 4
])

print("=== Organización Original: Filas = Estudiantes ===")
print(calificaciones)
print("\nPromedio por estudiante (axis=1):")
print(np.mean(calificaciones, axis=1))

# Transponer para analizar por materia
calificaciones_T = calificaciones.T

print("\n=== Después de Transponer: Filas = Materias ===")
print(calificaciones_T)
print("\nPromedio por materia (axis=1):")
print(np.mean(calificaciones_T, axis=1))

# Uso práctico: Detectar materia más difícil
materias = ['Matemáticas', 'Física', 'Química']
promedios_materias = np.mean(calificaciones_T, axis=1)
materia_dificil_idx = np.argmin(promedios_materias)

print(f"\nMateria más difícil: {materias[materia_dificil_idx]}")
print(f"Promedio: {promedios_materias[materia_dificil_idx]:.2f}")

---

## Ejercicios de Práctica

In [ ]:
# EJERCICIO 1: Transposición Básica
# Crea una matriz 2x4 con números del 1 al 8
# a) Transpónla
# b) Verifica que las dimensiones se invirtieron (2x4 → 4x2)
# c) Multiplica la matriz original por su transpuesta (usa np.dot)

# Tu código aquí:
matriz_a = np.arange(1, 9).reshape(2, 4)
transpuesta_matriz_a = matriz_a.T

# Verificación de las matrices
print("Matriz original:")
print(matriz_a)
print('-' * 100 )
print("Matriz transpuesta:")
print(transpuesta_matriz_a)
print('-' * 100 )

# Verificación de las dimensiones
print('Dimensiones Matriz')
print(matriz_a.shape)
print('-' * 100 )

print('Dimensiones Transpuesta')
print(transpuesta_matriz_a.shape)
print('-' * 100 )

# Multiplicación de matrices.
matriz_por_transpuesta = np.dot(matriz_a, transpuesta_matriz_a)
print('Matriz original multiplicada por su transpuesta:')
print(matriz_por_transpuesta)


In [ ]:
# EJERCICIO 2: Reshape con Restricciones
# Crea un array de 24 elementos (1 a 24)
# a) Reshape a 4x6
# b) Reshape a 2x12
# c) Reshape a 3x8
# d) Intenta reshape a 5x5 y captura el error

# Tu código aquí:

array_a = np.arange(1, 25)

# Aplicación del reshape
# a) Reshape a 4x6
reshape_a = array_a.reshape(4, 6)
reshape_b = array_a.reshape(2, 12)
reshape_c = array_a.reshape(3, 8)
print("Array original:")
print(array_a)
print('-' * 100)
print("Array reshaped a 4x6:")
print(reshape_a)
print('-' * 100)
print("Array reshaped a 2x12:")
print(reshape_b)
print('-' * 100)
print("Array reshaped a 3x8:")
print(reshape_c)
print('-' * 100)

try:
    # Intentar reshape a 5x5 pero sabemos que va a dar error
    reshape_d = array_a.reshape(5, 5)
    print("Array reshaped a 5x5:")
    print(reshape_d)
except ValueError as e:
    print("El número de elementos no coincide con la forma deseada:", e)



In [ ]:
# EJERCICIO 3: Inversión de Secuencias
# Tienes datos de temperatura de 7 días: [22, 24, 23, 25, 26, 24, 23]
# a) Invierte el array (último día primero)
# b) Invierte solo los primeros 5 días
# c) Crea un array con días pares en orden inverso

# Tu código aquí:

temperaturas = np.array([22, 24, 23, 25, 26, 24, 23])
temperaturas_invertido = temperaturas[::-1]
print("Temperaturas originales:")
print(temperaturas)
print('-' * 100)
print("Temperaturas invertidas:")
print(temperaturas_invertido)
print('-' * 100)

# Invertir los primeros 5
temperaturas[:5] = temperaturas[:5][::-1]
print("Inversión 5 elementos")
print(temperaturas)
print('-' * 100)

# Array con días pares en inverso
temperaturas = np.array([22, 24, 23, 25, 26, 24, 23])
mask_temperaturas = temperaturas % 2 == 0
temperaturas_pares = temperaturas[mask_temperaturas][::-1]
print("Temperaturas pares en orden inverso:")
print(temperaturas_pares)
print('-' * 100)

In [ ]:
# EJERCICIO 4: Flatten vs Ravel
# Crea una matriz 3x3 con números del 1 al 9
# a) Aplánala con flatten() y modifica el primer elemento
# b) Verifica que la matriz original NO cambió
# c) Aplánala con ravel() y modifica el primer elemento
# d) Verifica que la matriz original SÍ cambió

# Tu código aquí:

matriz_b = np.arange(1,10).reshape(3,3)
print("Matriz original:")
print(matriz_b)
print('-' * 100)

aplanada_b = matriz_b.flatten()
aplanada_b[0] = 999
print("Matriz aplanada con flatten():")
print(aplanada_b)
print('-' * 100)

# Validación de que no cambio la original
print("Matriz original:")
print(matriz_b)
print('-' * 100)

aplanada_b = matriz_b.ravel()
aplanada_b[0] = 999
print("Matriz aplanada con ravel():")
print(aplanada_b)
print('-' * 100)

# Verificación del cambio de la matriz original
print("Matriz original:")
print(matriz_b)
print('-' * 100)




In [50]:
# EJERCICIO 5: Pipeline Completo
# Simula una imagen RGB de 10x10 píxeles (10x10x3 por los canales R, G, B)
#
# a) Crea una matriz 10x10x3 con valores aleatorios entre 0-255
# b) Separa en 3 canales (Rojo, Verde, Azul)
# c) Aplana cada canal a vectores 1D
# d) Concatena los 3 vectores en uno solo (300 elementos)
# e) Reshape de vuelta a 10x10x3 para verificar

# Pista: usa array[:,:,0] para extraer canal rojo

# Tu código aquí:

# a) Crear matriz 10x10x3
np.random.seed(42)
imagen_rgb = np.random.randint(0, 256, size=(10, 10, 3))
print("Imagen RGB original:")
print("Forma:", imagen_rgb.shape)  # (10, 10, 3)
print('-' * 100)

# b) Separar en 3 canales
canal_rojo = imagen_rgb[:, :, 0]    # Matriz 10x10 (solo rojos)
canal_verde = imagen_rgb[:, :, 1]   # Matriz 10x10 (solo verdes)
canal_azul = imagen_rgb[:, :, 2]    # Matriz 10x10 (solo azules)

print("Canal Rojo:")
print("Forma:", canal_rojo.shape)  # (10, 10)
print(canal_rojo)
print('-' * 100)

print("Canal Verde:")
print("Forma:", canal_verde.shape)
print(canal_verde)
print('-' * 100)

print("Canal Azul:")
print("Forma:", canal_azul.shape)
print(canal_azul)
print('-' * 100)

# c) Aplanar cada canal a vectores 1D
rojo_flat = canal_rojo.flatten()    # 100 elementos
verde_flat = canal_verde.flatten()  # 100 elementos
azul_flat = canal_azul.flatten()    # 100 elementos

print("Canal Rojo aplanado:")
print("Forma:", rojo_flat.shape)  # (100,)
print("Primeros 10:", rojo_flat[:10])
print('-' * 100)

# d) Concatenar los 3 vectores en uno solo (300 elementos)
vector_completo = np.concatenate((rojo_flat, verde_flat, azul_flat))

print("Vector concatenado (R+G+B):")
print("Forma:", vector_completo.shape)  # (300,)
print("Total elementos:", len(vector_completo))
print("Primeros 10 (rojos):", vector_completo[:10])
print("Elementos 100-110 (verdes):", vector_completo[100:110])
print("Elementos 200-210 (azules):", vector_completo[200:210])
print('-' * 100)

# e) Reshape de vuelta a 10x10x3 para verificar
imagen_reconstruida = vector_completo.reshape(10, 10, 3)

print("Imagen reconstruida:")
print("Forma:", imagen_reconstruida.shape)  # (10, 10, 3)

# Verificación: ¿Son idénticas?
print("\n¿Imagen original == Imagen reconstruida?")
print(np.array_equal(imagen_rgb, imagen_reconstruida))  # False (orden diferente)

Imagen RGB original:
Forma: (10, 10, 3)
----------------------------------------------------------------------------------------------------
Canal Rojo:
Forma: (10, 10)
[[102  14 188 121  74 116 151  52 235 129]
 [ 20  57 235 218 169 187 189 189  54 248]
 [ 50  72 131  13   8 129 110 171 174  80]
 [103 253 105 220 217 201  13  14 214 189]
 [207 110 153 187  40  44  70 128 215 242]
 [162 122 230  27  71  32 150  36 103  34]
 [100 130 217 141 136  89 204  95  51 131]
 [150 142  35  70  85 169 184  27  43 189]
 [249 216 224  26 115   2 199  61  50 151]
 [117 215 112 185 253 130 112 186 129  86]]
----------------------------------------------------------------------------------------------------
Canal Verde:
Forma: (10, 10)
[[179 106  20 210 202  99 130   1 157 191]
 [160  21  88  58 255 207 189  50 243 130]
 [134 166  88 241  89  83 187 252  34 163]
 [131 133   3 190  43 189  94 199 251  39]
 [236  52 216 123 156  64   8 235  62  80]
 [162   4 249 134  11  47  61  98 213 192]
 [174   0 24