In [ ]:
import numpy as np
# Listas conjunto de objetos de trabajo

# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

# Puedes usar estos datos o crear los tuyos propios
laptops = np.array([45, 52, 48, 55, 60, 58, 62, 65, 70, 68, 72, 75])
smartphones = np.array([80, 85, 92, 95, 88, 102, 110, 108, 115, 112, 118, 120])
tablets = np.array([35, 38, 40, 42, 45, 48, 44, 46, 50, 52, 55, 58])
accesorios = np.array([150, 165, 180, 175, 190, 200, 210, 205, 220, 225, 230, 240])

# Mediana de datos
media_laptos = np.mean(laptops)
media_smartphones = np.mean(smartphones)
media_tablets = np.mean(tablets)
media_accesorios = np.mean(accesorios)

# Desviación Estandar de los datos 
std_laptos = np.std(laptops)
std_smartphones = np.std(smartphones)
std_tablets = np.std(tablets)
std_accesorios = np.std(accesorios)

# Maxima de datos 
maximo_laptos = np.max(laptops)
maximo_smartphones = np.max(smartphones)
maximo_tablets = np.max(tablets)
maximo_accesorios = np.max(accesorios)

# Minima de datos
minimo_laptos = np.min(laptops)
minimo_smartphones = np.min(smartphones)
minimo_tablets = np.min(tablets)
minimo_accesorios = np.min(accesorios)

# Total productos año por producto

total_laptos = np.sum(laptops)
total_smartphones = np.sum(smartphones)
total_tablets = np.sum(tablets)
total_accesorios = np.sum(accesorios)



In [ ]:
# Muestra de información, por producto

print("=======LAPTOS=======")
print(f"Mediana de inventario de Laptos:\n {media_laptos:.2f}")
print(f"Des Estandar de inventario de Laptos:\n {std_laptos:.2f}")
print(f"Maximo de inventario de Laptos:\n {maximo_laptos:.2f}")
print(f"Minimo de inventario de Laptos:\n {minimo_laptos:.2f}")
print(f"Total de inventario de Laptos:\n {total_laptos:.2f}")
print('-' * 200)

print("=======SMARTPHONES=======")
print(f"Mediana de inventario de smartphones:\n {media_smartphones:.2f}")
print(f"Des Estandar de inventario de smartphones:\n {std_smartphones:.2f}")
print(f"Maximo de inventario de smartphones:\n {maximo_smartphones:.2f}")
print(f"Minimo de inventario de smartphones:\n {minimo_smartphones:.2f}")
print(f"Total de inventario de smartphones:\n {total_smartphones:.2f}")
print('-' * 200)

print("=======TABLETS=======")
print(f"Mediana de inventario de tablets:\n {media_tablets:.2f}")
print(f"Des Estandar de inventario de tablets:\n {std_tablets:.2f}")
print(f"Maximo de inventario de tablets:\n {maximo_tablets:.2f}")
print(f"Minimo de inventario de tablets:\n {minimo_tablets:.2f}")
print(f"Total de inventario de tablets:\n {total_tablets:.2f}")
print('-' * 200)

print("=======ACCESORIOS=======")
print(f"Mediana de inventario de accesorios:\n {media_accesorios:.2f}")
print(f"Des Estandar de inventario de accesorios:\n {std_accesorios:.2f}")
print(f"Maximo de inventario de accesorios:\n {maximo_accesorios:.2f}")
print(f"Minimo de inventario de accesorios:\n {minimo_accesorios:.2f}")
print(f"Total de inventario de accesorios:\n {total_accesorios:.2f}")
print('-' * 200)

In [ ]:
# Análisis comparativo de inventarios

# Inventario por mes
inventario_total_mes = laptops + smartphones + tablets + accesorios
print(f"Total ventas por mes: {inventario_total_mes}")


# Información por trimestre de cada producto
print("=======LAPTOS=======")

Q1_laptops = laptops[:3]
Q2_laptops = laptops[3:6]
Q3_laptops = laptops[6:9]
Q4_laptops = laptops[9:]

print(f"Q1 de laptos: {Q1_laptops}, Q2 de laptos: {Q2_laptops}, Q3 de laptos: {Q3_laptops}, Q4 de laptos: {Q4_laptops} ")
print('-' * 200)

print("=======SMARTPHONES=======")

Q1_smartphones = smartphones[:3]
Q2_smartphones = smartphones[3:6]
Q3_smartphones = smartphones[6:9]
Q4_smartphones = smartphones[9:]

print(f"Q1 de smartphones: {Q1_smartphones}, Q2 de smartphones: {Q2_smartphones}, Q3 de smartphones: {Q3_smartphones}, Q4 de smartphones: {Q4_smartphones}")
print('-' * 200)

print("=======TABLETS=======")

Q1_tablets = tablets[:3]
Q2_tablets = tablets[3:6]
Q3_tablets = tablets[6:9]
Q4_tablets = tablets[9:]

print(f"Q1 de tablets: {Q1_tablets}, Q2 de tablets: {Q2_tablets}, Q3 de tablets: {Q3_tablets}, Q4 de tablets: {Q4_tablets}")
print('-' * 200)

print("=======ACCESORIOS=======")

Q1_accesorios = accesorios[:3]
Q2_accesorios = accesorios[3:6]
Q3_accesorios = accesorios[6:9]
Q4_accesorios = accesorios[9:]

print(f"Q1 de accesorios: {Q1_accesorios}, Q2 de accesorios: {Q2_accesorios}, Q3 de accesorios: {Q3_accesorios}, Q4 de accesorios: {Q4_accesorios}")
print('-' * 200)

# Calcular promedio por cada categoría de productos

print("=======LAPTOS=======")

quaters_laptos = np.split(laptops, 4)
mean_q1_laptos = np.mean(quaters_laptos[0])
mean_q2_laptos = np.mean(quaters_laptos[1])
mean_q3_laptos = np.mean(quaters_laptos[2])
mean_q4_laptos = np.mean(quaters_laptos[3])

print(f"Promedio de Q1 de laptos: {mean_q1_laptos:.2f}")
print(f"Promedio de Q2 de laptos: {mean_q2_laptos:.2f}")
print(f"Promedio de Q3 de laptos: {mean_q3_laptos:.2f}")
print(f"Promedio de Q4 de laptos: {mean_q4_laptos:.2f}")
print('-' * 200)

print("=======SMARTPHONES=======")

quaters_smartphones = np.split(smartphones, 4)
mean_q1_smartphones = np.mean(quaters_smartphones[0])
mean_q2_smartphones = np.mean(quaters_smartphones[1])
mean_q3_smartphones = np.mean(quaters_smartphones[2])
mean_q4_smartphones = np.mean(quaters_smartphones[3])

print(f"Promedio de Q1 de smartphones: {mean_q1_smartphones:.2f}")
print(f"Promedio de Q2 de smartphones: {mean_q2_smartphones:.2f}")
print(f"Promedio de Q3 de smartphones: {mean_q3_smartphones:.2f}")
print(f"Promedio de Q4 de smartphones: {mean_q4_smartphones:.2f}")
print('-' * 200)

print("=======TABLETS=======")

quaters_tablets = np.split(tablets, 4)
mean_q1_tablets = np.mean(quaters_tablets[0])
mean_q2_tablets = np.mean(quaters_tablets[1])
mean_q3_tablets = np.mean(quaters_tablets[2])
mean_q4_tablets = np.mean(quaters_tablets[3])

print(f"Promedio de Q1 de tablets: {mean_q1_tablets:.2f}")
print(f"Promedio de Q2 de tablets: {mean_q2_tablets:.2f}")
print(f"Promedio de Q3 de tablets: {mean_q3_tablets:.2f}")
print(f"Promedio de Q4 de tablets: {mean_q4_tablets:.2f}")
print('-' * 200)

print("=======ACCESORIOS=======")

quaters_accesorios = np.split(accesorios, 4)
mean_q1_accesorios = np.mean(quaters_accesorios[0])
mean_q2_accesorios = np.mean(quaters_accesorios[1])
mean_q3_accesorios = np.mean(quaters_accesorios[2])
mean_q4_accesorios = np.mean(quaters_accesorios[3])

print(f"Promedio de Q1 de accesorios: {mean_q1_accesorios:.2f}")
print(f"Promedio de Q2 de accesorios: {mean_q2_accesorios:.2f}")
print(f"Promedio de Q3 de accesorios: {mean_q3_accesorios:.2f}")
print(f"Promedio de Q4 de accesorios: {mean_q4_accesorios:.2f}")
print('-' * 200)


In [ ]:
# Mes más critico, cantidad de inventario bajo

mes_critico = np.min(inventario_total_mes)
indx_min = np.argmin(inventario_total_mes)
mes_critico_name = meses[indx_min]

print(f"El mes con el menor inventario es: {mes_critico_name}, con un total de stock de {mes_critico:.2f}")

# Mes peak, mes con mayor cantidad de inventario.

mes_peak = np.max(inventario_total_mes)
indx_max = np.argmax(inventario_total_mes)
mes_peak_name = meses[indx_max]

print(f"El mes con el mayor inventario es: {mes_peak_name}, con un total de stock de {mes_peak:.2f}")


In [ ]:
# Operaciones de tranformación

# Creando la matriz 2D con la información de las 4 categorías

inventario_matriz = np.array([laptops, smartphones, tablets, accesorios])
print(inventario_matriz)
print('-' * 200)

# Creando matriz 3D con la información necesaria
inventario_transpuesta = np.transpose(inventario_matriz)
inventario_3D = np.reshape(inventario_transpuesta, (2, 6, 4))
print(inventario_3D)
print('-' * 200)

# Encontrar el minimo y el maximo de toda la matriz
min_global = np.min(inventario_matriz)
max_global = np.max(inventario_matriz)

print(f"Valor mínimo de todo el inventario: {min_global}")
print(f"Valor máximo de todo el inventario: {max_global}")

inventario_normalizado = (inventario_matriz - min_global) / (max_global - min_global)
print("\nMatriz de inventario normalizada (valores entre 0 y 1):")
print(np.round(inventario_normalizado, 2))
print('-' * 200)

# ORDENAR: cada categoría de menor a mayor
inventario_ordenado = np.sort(inventario_matriz, axis=1)
print("\nInventario ordenado por categoría:")
print(f"Laptops ordenados: {inventario_ordenado[0]}")
print(f"Smartphones ordenados: {inventario_ordenado[1]}")
print(f"Tablets ordenadas: {inventario_ordenado[2]}")
print(f"Accesorios ordenados: {inventario_ordenado[3]}")
print('-' * 200)

# VARIACIÓN: mes a mes del inventario TOTAL
inventario_total_mensual = inventario_matriz.sum(axis=0)
variacion_mensual = np.diff(inventario_total_mensual)
print(f"\nVariación mensual del inventario total: {variacion_mensual}")
print(f"Interpretación: De mes 1 a mes 2 hubo un cambio de {variacion_mensual[0]} unidades")

In [53]:
# --- PASO 5: ANÁLISIS ESTADÍSTICO AVANZADO ---
print("\n--- PASO 5: ANÁLISIS ESTADÍSTICO AVANZADO ---\n")

# PERCENTILES: del inventario total mensual
p25, p50, p75 = np.percentile(inventario_total_mensual, [25, 50, 75])
print(f"Percentil 25 (Q1) del inventario total: {p25:.2f} unidades")
print(f"Percentil 50 (Mediana) del inventario total: {p50:.2f} unidades")
print(f"Percentil 75 (Q3) del inventario total: {p75:.2f} unidades\n")

# CORRELACIÓN: entre laptops y tablets
# La función devuelve una matriz, el valor de correlación está en la posición [0, 1]
correlacion = np.corrcoef(laptops, tablets)[0, 1]
print(f"Correlación entre Laptops y Tablets: {correlacion:.4f}")
print("Interpretación: Un valor cercano a 1 indica una fuerte relación positiva.\n")

# VALORES ATÍPICOS: del inventario total mensual
# Usamos el Rango Intercuartil (IQR)
iqr = p75 - p25
limite_inferior = p25 - 1.5 * iqr
limite_superior = p75 + 1.5 * iqr

# Creamos una máscara booleana para encontrar los valores fuera de los límites
mascara_atipicos = (inventario_total_mensual < limite_inferior) | (inventario_total_mensual > limite_superior)

if np.any(mascara_atipicos):
    print(f"Meses con inventario atípico: {meses[mascara_atipicos]}")
else:
    print("No se encontraron meses con valores de inventario atípicos.")

print('-' * 200)


--- PASO 5: ANÁLISIS ESTADÍSTICO AVANZADO ---

Percentil 25 (Q1) del inventario total: 365.25 unidades
Percentil 50 (Mediana) del inventario total: 416.00 unidades
Percentil 75 (Q3) del inventario total: 455.50 unidades

Correlación entre Laptops y Tablets: 0.9443
Interpretación: Un valor cercano a 1 indica una fuerte relación positiva.

No se encontraron meses con valores de inventario atípicos.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


In [55]:
# --- PASO 6: INDEXACIÓN Y FILTRADO AVANZADO ---
print("\n--- PASO 6: INDEXACIÓN Y FILTRADO AVANZADO ---\n")

# INVENTARIO SEGUNDO SEMESTRE: de Julio (índice 6) en adelante
inv_segundo_semestre = inventario_matriz[:, 6:]
print("Inventario del segundo semestre (Julio a Diciembre):")
print(inv_segundo_semestre)
print()

# MESES DE ALTO INVENTARIO: total > 400 unidades
meses_alto_inv = meses[inventario_total_mensual > 400]
print(f"Meses con inventario total superior a 400 unidades: {meses_alto_inv}\n")

# CATEGORÍAS CRÍTICAS: algún mes tuvieron < 80% de su promedio anual
print("Categorías que tuvieron un inventario crítico (<80% del promedio) en algún mes:")
# Creamos un diccionario para iterar fácilmente
categorias = {'Laptops': laptops, 'Smartphones': smartphones, 'Tablets': tablets, 'Accesorios': accesorios}
for nombre, data in categorias.items():
    promedio_anual = data.mean()
    limite_critico = 0.8 * promedio_anual
    # np.any() comprueba si alguna vez se cumple la condición
    if np.any(data < limite_critico):
        print(f"- {nombre}")
print()

# PATRÓN ESTACIONAL: extraemos datos de temporada alta (marzo, junio, sep, dic)
indices_temporada_alta = [2, 5, 8, 11] # Índices para Marzo, Junio, Septiembre, Diciembre
inv_temporada_alta = inventario_matriz[:, indices_temporada_alta]
print(f"Inventario en meses de temporada alta ({meses[indices_temporada_alta]}):")
print(inv_temporada_alta)
print()

# COMPARACIÓN CRUZADA: smartphones > 100 Y laptops > 60
meses_cruzados = meses[(smartphones > 100) & (laptops > 60)]
print(f"Meses donde los smartphones superaron las 100 uds Y las laptops las 60 uds: {meses_cruzados}")

print('-' * 200)


--- PASO 6: INDEXACIÓN Y FILTRADO AVANZADO ---

Inventario del segundo semestre (Julio a Diciembre):
[[ 62  65  70  68  72  75]
 [110 108 115 112 118 120]
 [ 44  46  50  52  55  58]
 [210 205 220 225 230 240]]

Meses con inventario total superior a 400 unidades: ['Junio' 'Julio' 'Agosto' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']

Categorías que tuvieron un inventario crítico (<80% del promedio) en algún mes:
- Laptops
- Smartphones
- Tablets
- Accesorios

Inventario en meses de temporada alta (['Marzo' 'Junio' 'Septiembre' 'Diciembre']):
[[ 48  58  70  75]
 [ 92 102 115 120]
 [ 40  48  50  58]
 [180 200 220 240]]

Meses donde los smartphones superaron las 100 uds Y las laptops las 60 uds: ['Julio' 'Agosto' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


In [56]:
# --- PASO 7: VISUALIZACIÓN DE RESUMEN ---
print("\n--- PASO 7: REPORTE FINAL DE INVENTARIO ---\n")

# MATRIZ DE RESUMEN
# [Categoría, Promedio Anual, Total Anual, Mes Peak, Valor Peak]
resumen_data = []
nombres_categorias = list(categorias.keys())

for nombre, data in categorias.items():
    promedio = data.mean()
    total = data.sum()
    idx_peak = data.argmax()
    mes_peak = meses[idx_peak]
    valor_peak = data[idx_peak]
    resumen_data.append([nombre, f"{promedio:.1f}", total, mes_peak, valor_peak])

print("Matriz de Resumen:")
print("['Categoría', 'Promedio Anual', 'Total Anual', 'Mes Peak', 'Valor Peak']")
for row in resumen_data:
    print(row)
print()

# RANKING DE CATEGORÍAS por volumen total anual
totales_anuales = inventario_matriz.sum(axis=1)
# argsort nos da los índices que ordenarían el array, y [::-1] los invierte para orden descendente
indices_ranking = np.argsort(totales_anuales)[::-1]
ranking = np.array(nombres_categorias)[indices_ranking]
print(f"Ranking de Categorías por Volumen Anual: {', '.join(ranking)}\n")

# PORCENTAJE que representa cada categoría del inventario total anual
inventario_total_general = totales_anuales.sum()
print("Porcentaje del Inventario Total Anual:")
# Iteramos sobre los índices ya ordenados por el ranking
for i in indices_ranking:
    nombre = nombres_categorias[i]
    porcentaje = (totales_anuales[i] / inventario_total_general) * 100
    print(f"- {nombre}: {porcentaje:.2f}%")


--- PASO 7: REPORTE FINAL DE INVENTARIO ---

Matriz de Resumen:
['Categoría', 'Promedio Anual', 'Total Anual', 'Mes Peak', 'Valor Peak']
['Laptops', '60.8', np.int64(730), np.str_('Diciembre'), np.int64(75)]
['Smartphones', '102.1', np.int64(1225), np.str_('Diciembre'), np.int64(120)]
['Tablets', '46.1', np.int64(553), np.str_('Diciembre'), np.int64(58)]
['Accesorios', '199.2', np.int64(2390), np.str_('Diciembre'), np.int64(240)]

Ranking de Categorías por Volumen Anual: Accesorios, Smartphones, Laptops, Tablets

Porcentaje del Inventario Total Anual:
- Accesorios: 48.80%
- Smartphones: 25.01%
- Laptops: 14.90%
- Tablets: 11.29%
